title: The Impact of Task Underspecification in Evaluating Deep Reinforcement Learning
description: Advances in Neural Information Processing Systems (NeurIPS) 2022
buttons:
  Paper: 'https://arxiv.org/abs/2210.08607'
  Video: ''
  Open Reveiw: ''
  Cite: '#citation'
  Authors: '#authors'
google_analytics: ''
