title: The Impact of Task Underspecification in Evaluating Deep Reinforcement Learning
description: Advances in Neural Information Processing Systems (NeurIPS) 2022
buttons:
  Paper: 'https://arxiv.org/abs/2210.08607'
  Poster: 'assets/poster.pdf'
  Video: 'https://nips.cc/virtual/2022/poster/52798'
  Slides: 'assets/slides.pdf'
  Open Review: 'https://openreview.net/forum?id=F_9w7Wl78IH'
  Cite: '#citation'
  Authors: '#authors'
google_analytics: ''
